dis-moi/backend

- app/config/services.yml
- src/AppBundle/Serializer/ContributorNormalizer.php
- src/AppBundle/Serializer/NoticeNormalizer.php
- src/Domain/Service/NoticeUrlGenerator.php
- web/config.php
Add a Notice URI generator service. I think it's more a URI (Unique Resource Identifier) rather than an URL.
> feat(contributor): Expose notices URIs in contributors and notices

- app/DoctrineMigrations/Version20200611102324.php
- app/Resources/translations/messages.fr.yml
- app/Resources/views/easy_admin/notice_in_list.html.twig
- app/Resources/views/easy_admin/vich_uploader_image.html.twig
- app/Resources/views/easy_admin/vich_uploader_screenshot.html.twig
- app/config/config.yml
- app/config/easyadmin.yml
- src/AppBundle/Controller/AdminController.php
- src/AppBundle/Controller/ContributorAdminController.php
- src/AppBundle/Entity/Contributor.php
- src/AppBundle/Entity/Notice.php
This adds:
- screenshot image to notice
- banner image to contributor
- starred notice to contributor
> feat: add screenshot to notice, starredNotice and banner to Contributor

- Makefile
:nail_care: but I had to launch tests as in CI setup so it helped a lot, also I think the CI setup command are wrong : `composer install` should be run from inside the container.
> Also I'm very sorry I did merge new notices endpoint PR because I was badly needing it, and I didn't notice tests were failing and pushed few sneaky commits on develop to fix them, see comment in b665b0bf945af0c21d2bee9f77adec8d5f6f366c and commit 3aaeaaab7b6141595c3481ee22a1852f436f0b62
> chore: Add a Makefile

- src/AppBundle/Repository/NoticeRepository.php
API endpoint /notices?contributor=X is currently broken :-(
> fix(api): get notices by contributor

- app/DoctrineMigrations/Version20200924094631.php
- app/Resources/translations/messages.fr.yml
- app/config/easyadmin.yml
- src/AppBundle/Controller/Api/GetCategories.http
- src/AppBundle/Controller/Api/GetCategoriesAction.php
- src/AppBundle/DataFixtures/ORM/LoadContributorData.php
- src/AppBundle/Entity/Contributor.php
- src/AppBundle/Form/CategoryNameType.php
- src/AppBundle/Repository/BaseRepository.php
- src/AppBundle/Repository/CategoryRepository.php
- src/AppBundle/Repository/ContributorRepository.php
- src/AppBundle/Repository/DomainNameRepository.php
- src/AppBundle/Repository/ExtensionRepository.php
- src/AppBundle/Repository/MatchingContextRepository.php
- src/AppBundle/Repository/NoticeRepository.php
- src/AppBundle/Repository/RatingRepository.php
- src/AppBundle/Repository/RestrictedContextRepository.php
- src/AppBundle/Repository/SubscriptionRepository.php
- src/AppBundle/Serializer/ContributorNormalizer.php
- src/Domain/Factory/CategoryFactory.php
- src/Domain/Model/Category.php
- src/Domain/Model/Enum/CategoryName.php
Add an API route to list the categories
Map categories to contributor entity
Update Contributor admin page
Update fixtures
> feat: Introduce contributor's categories

- app/DoctrineMigrations/Version20201007100028.php
- app/DoctrineMigrations/Version20201007120011.php
- app/Resources/translations/messages.fr.yml
- app/config/config.yml
- app/config/easyadmin.yml
- src/AppBundle/DataFixtures/ORM/LoadContributorData.php
- src/AppBundle/Entity/Contributor.php
- src/AppBundle/Serializer/ContributorNormalizer.php
- web/config.php
To show a preview when shared on social medias
> feat(Contributor): Add a preview image to a contributor.

- src/AppBundle/Entity/Contributor.php
- src/AppBundle/Entity/Extension.php
- src/AppBundle/Entity/Notice.php
- tests/AppBundle/Entity/NoticeTest.php
- tests/FixtureAwareWebTestCase.php
@JalilArfaoui I added tests, but even the test which add a relayer is failing and shouldn't.
Are these tests flawed?
Anyway, I tried to solving the issue preventing the deletion of a relayer but couldn't get it to work properly...
Could you have a look?
As a shortcut to run the tests you may use:
```
make
make test
```
> https://trello.com/c/jPINYfEW/646-impossible-de-supprimer-des-relayeurs
> chore(relayer): Add tests add/remove a relayer

- src/Domain/Model/Enum/CategoryName.php
I made a mistake last time on the name.
> correct label : culture et société

- docs/xpath.md
- migrations/Version20201118151915.php
- src/DataFixtures/DomainFixtures.php
- src/DataFixtures/MatchingContextFixtures.php
- src/DataFixtures/NoticeFixtures.php
- src/Entity/MatchingContext.php
- src/Form/MatchingContextType.php
- src/Helper/ArrayHelper.php
- src/Serializer/MatchingContextNormalizer.php
- tests/e2e/GetMatchingContextsTest.php
- tests/e2e/GetNoticesTest.php
- translations/messages.fr.yml
> https://github.com/dis-moi/extension/pull/736
> feat(matcher): Add the ability to match based on an XPath expression

- src/Entity/Notice.php
- src/Entity/Rating.php
- src/Helper/ArrayHelper.php
- src/Helper/CollectionHelper.php
- src/Helper/StringHelper.php
I just ran `make cs-fix` was fed up with this leftover diff.
> fix: Code style

- .env
- CONTRIBUTING.md
- README.md
- alias
> Goutte's review 00

- migrations/Version20210416155713.php
- src/Entity/MatchingContext.php
> fix(xpath): Set xpath field type to text

- config/packages/vich_uploader.yaml
> fix: uploading files during creation of Contributor

- src/Serializer/ContributionDenormalizer.php
- tests/e2e/PostContributionTest.php
Fixes https://github.com/dis-moi/extension/issues/940
> fix(contribution): Fix asking a question to a specific contributor

- src/Command/UpdateCaptainFactNoticesCommand.php
Retrieve youtube domain id & archive newly irrelevant notices
These were old issues I never commited, my bad. It explains why the automation doesn't work... the youtube domain id wasn't ever retrieved.
Thanks in advance for your quick review :)
> debug on CaptainFact automation

- Makefile
- migrations/Version20210615164457.php
- src/Entity/Contributor.php
> feat(contributor): extend intro length

- migrations/Version20210519132610.php
> fix(migration): locale fr

- src/Domain/Service/SubscriptionsTrackingService.php
Will fix some of the `422 Unprocessable Entity` errors.
> fix(subscription): Fix empty subscription update date crash

- docs/matching_contexts_flow.mmd
> doc: add matching contexts flow

- CONTRIBUTING.md
- config/packages/api_platform.yaml
- config/packages/framework.yaml
- config/packages/security.yaml
- config/routes/api_platform.yaml
- config/routes/jwt.yaml
- docs/using_api_v4.md
- src/OpenApi/Documenter/JwtDocumenter.php
- tests/e2e/AuthenticationTest.php
- tests/e2e/GetNoticesTest.php
fix path to v4 API
fix authentication test
fix jwt doc
> fix(api-v4): fix various authentication config bugs

- composer.lock
- src/Entity/Notice.php
- src/OpenApi/Documenter/JwtDocumenter.php
Mostly when creating/updating a notice.
@JalilArfaoui could you review the properties description and tell me if they are accurate?
> for reference https://github.com/dis-moi/backend/issues/112
> chore(api): don't allow stats count edition from the API

- docs/openapi.json
- docs/using_api.md
- docs/using_api_v4.md
- src/DataFixtures/NoticeFixtures.php
- tests/e2e/GetNoticeTest.php
> see https://github.com/dis-moi/backend/issues/417
> chore: Rename occurences of bulles.fr domain

- composer.lock
- src/OpenApi/Documenter/JwtDocumenter.php
Updating api platform fixed an issue with a wrong `requestBody` type in the oas file.
> see https://github.com/api-platform/core/issues/4080
> Oas file fixes

- migrations/Version20210902124326.php
- src/DataFixtures/DomainFixtures.php
- src/Entity/DomainName.php
> fix #432
> I wanted to create a protodomaine : www.zalando.fr/sneakers
> but since www.zalando.fr already exists, Easyadmin blocks me.
> feat(domain): allow duplicated domain names

- src/Entity/DomainName.php
> fix(domain): allow duplicated domain names
